# Generated by Django 4.1.3 on 2023-07-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registerId',
            field=models.IntegerField(),
        ),
    ]
